### ISSUE TITLE
[blocked] CamelotPair explorer contract verification

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#163]
https://goerli.arbiscan.io/address/0x2a09411c7208c6ddcec0fe8e3e58841f5f0f2030

The CamelotPair is not verified during the deployment process

- [ ] Update the dexpool scripts to also verify the contracts
- [ ] Possible to do this for factory generated contracts?

**Comment by daopunk** [comment]
pretty much blocked by Camelot. if they verify their AlgebraPool contract one time, every deployment from the factory will be verified, but they haven't... i can see the code in link below, but only as an inherited contract to the AlgebraPoolDeployer, which is verified (hence why we can see this). so it may be possible to copy-paste the code from here and verify ourselves (from another repo, since it breaks at ^0.8.0), but that requires also finding and verifying all it's inherited interfaces and libraries, which there are more than a few.

also, Camelot discord has not been responsive for awhile. i have no idea when or if they plan on verifying their code

https://goerli.arbiscan.io/address/0xe0e840C629402AB33433D00937Fe065634b1B1Af#code

**Comment by pi0neerpat** [comment]
Contacting Camelot for more support

**Comment by daopunk** [comment]
in a local repo with compiler set to 0.7.6, attempt was made to verify contracts, but was not successful.

however, AlgebraPool is verified on Arbitrum mainnet

**Comment by daopunk** [comment]
cannot get this to verify for some reason. i think it's a Arbitrum - Forge related issue when i try using 0.7.0 compiler, but not really sure.

so, i reached out to the Algebra Telegram community and asked that they verify this

**Comment by pi0neerpat** [comment]
Connecting with algrebra team via camelot into

**Comment by pi0neerpat** [comment]
Closing since moving to Sepolia Testnet. Plan will be to deploy it ourselves and verify.

CamelotPair is using constructor rather than initialize, which makes verification more difficult. Solution:

1. Deploy protocol ourselves, swap out pool constructor for initialize
2. Add verification script for after a factory child is created.
