### ISSUE TITLE
Set inital camelot pool price

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#164]
Currently, the `systemCoinOracle` is failing, since `CamelotRelayer.getResultWithValidity()` fails, since the pool price is 0 OD/WETH

- [ ] Add a testnet script to add OD and WETH to the camelot pool, and call `sync` , in order to set the initial price
- [ ]  Address comment in script/Deploy.s.sol L256: // TODO: how to set initial price of pool

```js
  function sync() external lock {
    uint token0Balance = IERC20(token0).balanceOf(address(this));
    uint token1Balance = IERC20(token1).balanceOf(address(this));
    require(token0Balance != 0 && token1Balance != 0, "CamelotPair: liquidity ratio not initialized");
    _update(token0Balance, token1Balance);
  }
```

Last Discord discussion was here https://discord.com/channels/943473409541685319/1103401706605248572/1154880173515218944

**Comment by daopunk** [comment]
so, i can deploy pools (without price initialization) from the factory, but in order to be able to call initialize, i need to deploy from the AlgebraPoolDeployer, which requires a DataStorage contract, which I don't have, but can see via inherited contracts at the link below. perhaps we can deploy and verify this ourselves from another repo at ^0.7.0

https://goerli.arbiscan.io/address/0x5Cd40c7E21A15E7FC2503Fffd77cF70c60628F6C#code

**Comment by pi0neerpat** [comment]
1. Try sync and see if price will be set by adding tokens
2. Verify that initialize cannot be called later

**Comment by daopunk** [comment]
confirmed. Camelot server responded that there is no equivalent to the `sync` function for the AlgebraPool
