### ISSUE TITLE
Unit Test: Accounting Engine

### ISSUE THREAD

**Issue by cupOJoseph** [open-dollar/od-contracts#182]
Depends on #214 

All tests relating to accounting engine tests should pass.

Main goal here to fix math now that surplus transfering is using WAD units.
Verify the correct amount of surplus is being transfered
`auctionSurplus` tests should be passing

**Comment by St4rgarden** [comment]
Test fix proposal:

# Fix for Accounting Engine Unit Testing

The unit tests for `test/unit/AccountingEngine.t.sol:Unit_AccountingEngine_AuctionSurplus` are currently failing due to a change in how internal balances are calculated.  Currently 8/9 of these test cases are failing.

## Considerations

The original GEB system uses the RAD units during calculations - this has been changed to WAD for the Open Dollar protocol.

I will start with the assumption that these tests should in fact be passing; and modify the test expectation calculations to align with the WAD math.  At that point all tests should be passing.  If for any reason the tests are not failing I will write this up as an issue and we will proceed with isolating and fixing any underlying calculation bug.

## Changes

- [] `test_Call_SAFEEngine_DebtBalance`
- [] `test_Call_SAFEEngine_SettleDebt`
- [] `test_Call_SurplusAuctionHouse_StartAuction`
- [] `test_Emit_AuctionSurplus`
- [] `test_Revert_InsufficientSurplus`
- [] `test_Revert_SurplusAuctionDelayNotPassed`
- [] `test_Revert_surplusTransferPercentageIs1`
- [] `test_Set_LastSurplusTime`

**Comment by pi0neerpat** [comment]
Looks good, let's move ahead

**Comment by pi0neerpat** [comment]
For visibility, I wanted to point out that there is an existing PR open to solve this https://github.com/open-dollar/od-contracts/pull/185

Please coordinate with Hunter on whether it should be continued, or replaced

**Comment by pi0neerpat** [comment]
Just FYI lets wait until #214 is complete before continuing on this one.
