### ISSUE TITLE
Research - NFT Marketplace

### ISSUE THREAD

**Issue by daopunk** [open-dollar/od-contracts#306]
Research top NFT Marketplaces (5 - 7 protocols) and checkout out code repos. Rate protocols by security, scalability, and organization of codebase.

I would assume we fork Seaport, but maybe there are better options. Also, @cupOJoseph (and @St4rgarden) has contributed to Seaport: https://github.com/ProjectOpenSea/seaport-core/tree/main

Questions to guide research:
- Does the NFT marketplace have its own code base or is it a fork?
- Have there been exploits in the past or has the protocol been consistently secure?
- Is the protocol on Arbitrum or well-suited for Arbitrum?
- Is the codebase organized and easily forkable? (single repo, developer docs, commented code, accessible community, etc.)

Goal:
Decide on a marketplace to fork into Open Dollar which we will modify to include hashed states of NFVs in the market attributes and enforce state checks before transactions.

**Comment by St4rgarden** [comment]
Honestly I don't think that building a OD marketplace specifically for the OD NFVs is the best idea in the short or medium term.  This is because there's significant traction and exposure that could be gained by getting OD's NSVs directly on OpenSea.  All the other markets aggregate from OpenSea as well - so if you can get the NFTs listed directly on OpenSea you can get them listed across all the top marketplaces.

My thought process on the front-running issue is that there's actually no way securely to "checkpoint" the NSV using the standard practices for NFT marketplaces IE signature based standard meta-transactions using a Seaport order.  Every way I have considered doing it requires a transaction before the order is made - but unfortunately I do not believe there's a way to prevent a spoof of the signature.

Since the Seaport order is oblivious to the state of the NSV Safe, and the SafeEngine is also oblivious to the NSV - I don't see a clear path for this which is secure without enforcing an escrow within the `from` and `to` fields of the `transfer` function.

If the only way to transfer an NSV is either into or out of the Escrow contract - then we can safely checkpoint NSV state by the Escrow contract, issue valid orders via Seaport and the Opensea API which will display correctly on Opensea's front end AND then enforce the order at the point of checkout using EIP1271.

Freely transferable NSVs are an absolute scary nightmare guys I cannot overstate this enough.  Millions of dollars in user funds could be at risk.

**Comment by pi0neerpat** [comment]
Decided on Seaport + ERC7496
