### ISSUE TITLE
Safe manager upgrade plan

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#323]
We have decided to not implement any code changes for issue #232. Rather, we will devise a plan for how to perform a safe manager upgrade and avoid the original issue raised in the code audit. I believe this is sufficient to address the audit finding. 

Please write a comprehensive set of instructions for our team and the dao on how to upgrade the safe manager, per Joseph's high-level outline here:

> 1. create a new safemanager that can only be started by the DAO
> 2. the DAO votes to update the address for the ODSafeManager and start the new one
> 3. as part of calling the start function on the new ODSafeManager it copies over all the data it needs, and some of it can already be pre-written into it
> 4. the old ODSafeManager still exists but is no longer connected to anything nor has any special permissions

The key elements of the above plan are that:
- Data integrity is maintained throughout the upgrade without needing to "pause" the protocol. Eg. ownership cannot be lost or manipulated during the upgrade
- The governance process may take multiple days between when contracts are deployed, and when proposal is executed. Again, data integrity should be maintained. The suggestion is to copy the data in the same moment as the safe manager is changed. This may require additional contract(s). 

You're welcome to organize it however you see fit, but here is my suggested format:

## Overview

_Explain the high level process, so the average defi user can understand_

## Code Audit fix

_How this addresses the potential issues raised in "#381 updating address Vault721.safeManager breaks NFV minting"_

## Operational Steps

_A clear and concise set of procedures, expanding on Joseph's outline. Please include code snippets, psuedo-code, and recommendations for additional research in any areas you are unsure of._ 

## Risks and Security

_Discuss security concerns, potential pitfalls to be aware of, and any additional security risks associated with the process_

**Comment by St4rgarden** [comment]
## Technical Overview

The ODSafeManager is designed to be quasi-upgradeable.  That means we need a way to migrate all required state from previous deplyoments of the ODSafeManager.

I propose a simple sequential migration by safeId.  Each individual safe will be processed in order by safeId.  We extract all of the required data such as `safeData`, `owner`, `handler`, `cType` as well as the information about users / owners such as `usrSafes` and `usrSafesPerCollat`.  The downside is that there would be a short delay between deploying, initializing and migrating the data.  I believe there's simply too much data to migrate inside a single block - so this could look like a 1-2 hour window where SAFE changes from the Manager will be "down".

We also have to pass in existing previous permissions; validate them against the previous permissions.  The reason for this is because the `caller` permissions for `handlerCan` and `safeCan` are not natively enumerable.

While permissions can be re-assigned by users themselves without "bricking" anything; it would be incredibly helpful for our user base to also transfer all permissions.

I considered a merkle tree implementation as well - but it just felt a bit more centralized, risky and error prone.  

## High Level Overview

In order to upgrade the Open Dollar Safe Manager contract; we need to migrate all of the previous Safe data.  This means that we will be batching some transactions that pull the previous Safe data directly into the new Manager contract.  There could be a very brief interruption during the data migration.  

## Structs:

```solidity
  struct SAFEData {
    // Address of the safe owner
    address owner;
    // Address of the safe handler
    address safeHandler;
    // Collateral type of the safe
    bytes32 collateralType;
  }

    struct Set {
        // Storage of set values
        bytes32[] _values;
        // Position of the value in the `values` array, plus 1 because index 0
        // means a value is not in the set.
        mapping(bytes32 => uint256) _indexes;
    }
```

Wrapper struct for Set used in ODSafeManger:

```solidity
    struct UintSet {
        Set _inner;
    }
```

## Required Data:

```solidity
  uint256 internal _safeId; // Auto incremental
  mapping(address _safeOwner => EnumerableSet.UintSet) private _usrSafes;
  /// @notice Mapping of user addresses to their enumerable set of safes per collateral type
  mapping(address _safeOwner => mapping(bytes32 _cType => EnumerableSet.UintSet)) private _usrSafesPerCollat;
  /// @notice Mapping of safe ids to their data
  mapping(uint256 _safeId => SAFEData) internal _safeData;

  /// @inheritdoc IODSafeManager
  mapping(address _owner => mapping(uint256 _safeId => mapping(address _caller => bool _ok))) public safeCan;
  /// @inheritdoc IODSafeManager
  mapping(address _safeHandler => mapping(address _caller => bool _ok)) public handlerCan;
  /// @inheritdoc IODSafeManager
  mapping(address _safeHandler => bool _exists) public handlerExists;
```

Migrating old state from a previous incarnation of ODSafeManager requires the following data:

- `_safeId` the total number of safes opened by the previous ODSafeManager
- `usrSafes` the set of all safeIds for a particular owner address
- `_usrSafesPerCollat` the total number of safes owned by a particular address for a given collateral type
- `_safeData` for each safe we must know the owner, collateral type and handler which are encoded on the SAFEData struct.
- `handlerExists` whether a particular address is in fact a safe handler

- The two trickiest ones are the `handlerCan` and `safeCan` mappings because there is no way to simply enumerate them.  We need to pull the permissions data from the event logs in order to manually pass in these addresses.  Then before we can pull any data from the old manager to the new manager; we have to check these permissions in a migration function in order to validate them at the time of migration.


## Migration function requirement on existing ODSafeManager

If we decide to actually access and copy the data directly from the previous ODSafeManager; we will need to write a migration function.  The reason is because several of the data mappings are either private or internal; and will not be accessible from an external contract or address.

This can be done with a migration flag and address mapping:

```solidity
address newODSafeManager;
```

```solidity
function migrate(uint256 _safeId, address safeCallerCans[], address safeHandlerCans[]) external returns (SAFEData safeData, EnumerableSet.UintSet usrSafes, EnumerableSet.UintSet usrSafesPerCollat) {
    if (newODSafeManager != msg.sender) revert;
    safeData = _safeData[_safeId];
    usrSafes = _usrSafes[safeData.owner];
    usrSafesPerCollat = _usrSafesPerCollat[safeData.owner];
    for (i == 0; i < safeCallerCans.length; i++) {
        if (safeCan[safeData.owner][_safeId][safeCallerCans[i]] != true) revert;
    }
    for (i == 0; i < safeHandlerCans.length; i++) {
        if (handlerCan[safeData.handler][safeHandlerCans[i]] != true) revert;}
}
```
The function is access control; and can only be called *after* governance has approved a migration to a new ODSafeManager.

Essentially we use the safeId to access most of the safe data - and then iterate through a supplied two supplied sets of potentially authorized addresses.  We revert if any of the data is not correct.  We could also pop the incorrect addresses.

Of course we will also need a function on the new ODSafeManager which is something like:

```solidity
function migratePull(uint256 safeBatchSize, address[][] safeCans, address handlerCans[][]) public {
  uitn256 safeId = _safeId;
  for (i = 0; i < safeBatchSize; i++) {
       safeId = safeId++;
      (SAFEData safeData, uint256 usrSafes, uint256 usrSafesPerCollat) = prevODSafeManager.migrate(safeId, safeCans[i], handlerCans[i]);
      _safeData[safeId] = safeData;
      if (handlerExists[safeData.handler] == false) {
        handlerExists[safeData.handler] == true}
      if (usrSafes[safeData.owner] == 0) {
        usrSafes[safeData.owner] = usrSafes;}
      if (usrSafesPerCollat[safeData.owner] == 0) {
        usrSafesPerCollat[safeData.owner] = usrSafesPerCollat;}
      _setSafeCans(safeId, safeCans);
      _setHandlerCans(safeId, handlerCans, safeData.handler);}
  _safeId = safeId;
```

This is a naive implementation because I think it makes much more sense to iterate through each individual safe in order; and reassign the `_safeId` at the end of each completed batch of migrations.


## Enumeration starting from the SafeId

For each `safeId` there is only one collateral type, one owner and one handler.

---

The `safeId` by itself returns significant data:

`_safeData(safeId)` returns the SAFEData object with owner, safeHandler and cType.

---

We can then use `owner` to get the `EnumerableSet.UintSet` from `_usrSafes(owner)`

---

We can also get the user safe by collateral using `_userSafesPerCollat(owner, cType)`

---

We also can set the handler exists `handlerExists(safeHandler)`

---

This leaves us with only the `caller` fields missing from both `safeCan` and `handlerCan`

---

We also have to account for the fact that there can be multiple `caller` per safe and they can either be mapped starting from the handler or the owner.

---

## Caller permissions are not discoverable from safeId

We can actually migrate almost all of the data from the previous ODSafeManager using only the `safeId`; with the exception of the permissioning.  Only `safeCan` and `handlerCan` data is non-discoverable.

So this kind of begs the question: do we also need to transfer all of the permissions across before "starting" the new ODSafeManager?

I think so.

## Requirements:

- Previous ODSafeManager is disabled after changing the ODSafeManager address on the Vault721 contract by governance.
- Once the new ODSafeManager is authorized from the Vault721; it begins in a "locked" state.
- While locked the new ODSafeManager cannot be called for anything other than initialization and migration purposes.
- The new ODSafeManager cannot be unlocked until it's `_safeId` is equal to the previous ODSafeManager contract's `_safeId`.
- There's a `migrate` function on each ODSafeManager; which allows the private and internal virables / mappings to be exposed during the migration period; on the previously used ODSafeManager.
- There's a `migratePull` function on the new ODSafeManager; which allows the new manager to call into the previous manager ... and then to validate external data IE the `handlerCans` and `safeCans`.  But also to pull the true from the previous ODSafeManager contract.
- There's a `setMigration` function which allows a previous ODSafeManager to target a the new ODSafeManager `newODSafeManager`
- An `unlock` function which checks that the current `_safeId` on the new ODSafeManager is equal to the `_safeId` on the previous ODSafeManager.  Because everything is linear and sequential; when the `_safeId`s match ... the migration is complete.
- We may also want a `migratePermissions` function; because in the current design migrating data is not access controlled at all.  It's completely permissionless.  So if someone starts randomly calling `migratePull` without passing in user's previous permissioned callers and handlers - we still want a way to migrate the permissions after the fact.  The alternative is making the `migrationPull` function access control.

## Risks and Security

The reason I chose this process instead of a merkletree implementation was it has a lot less risks and much more enforceable data integrity.  The downside being that we can only fit so much data in blocks; and therefore there is a chance that the migration could take more than 1 block and cause the Manager to be "paused" for a short time.  I understand that not pausing the protocol was part of the requirement but I think that the pros outweigh the cons in this case.

The biggest risks in a data migration like this are:

- New permissions somehow "sneak" in enabling a malicious user to affect someone else's safe.
- A safe is "forgotten" and is left out of the migration rendering it broken.  Although the collateral could still be recovered by delegatecall from the proxy owner.
- Data corruption; if the data somehow lost it's integrity it could render safes broken.
- Malicious data in a merkle tree; could reassign ownership of a Safe.

This is the biggest reason I wanted to do a sequential and linear process.  It's not very efficient but it's quite secure.  We know how many safes have been created - and we go through them one by one - copying each SAFE's data set over to the new manager.  Ideally we get the SAFE's permissions as well - although those can also be re-assigned by the user at any time.  Once we have gone through every single SAFE - we have all of the data from the previous contract.  Then we can "unlock" the new manager.

Another potential pitfall is that we miss user Safe permissions in a way that breaks other applications.  Perhaps another application believes that it is still correctly permissioned; and does not ask the user for a new approval from the new Safe Manager.

**Comment by pi0neerpat** [comment]
Thank you for taking the time to write this migration plan, and being thorough about the risks and challenges that we would face if a migration was needed. 

Based on my understanding, a change would be required in the ODSafeManager, in order to expose some private and internal variables.  Are there any other changes that would be required prior to protocol deployment?

Overall, I think this gives us a good picture of what would be required, and a path forward if we decide to pursue using the migration feature. Marking as complete, since this addresses the outstanding audit finding.

**Comment by St4rgarden** [comment]
> Thank you for taking the time to write this migration plan, and being thorough documenting the risks and challenges if a migration was needed.
> 
> Based on my understanding, a change would be required in the ODSafeManager, in order to expose some private and internal variables. Are there any other changes that would be required prior to protocol deployment?
> 
> Overall I think issue, along with the ideas presented in #271, gives us a good picture of what would be required. Marking as complete, since this addresses the outstanding audit finding by informing the DAO about the risks and effort required before any updates to the Safe Manager can be made.

I do not believe there's any other ***required*** changes prior to the protocol deployment.  However I believe the most squeaky clean way would be to "lock" the old ODSafeManager when it's disabled via the governance action.  The reason is because there are still actions that can be taken on the old safe manager - and reconciling the event logs between the old and new managers could be tedious.

Another reason is because the `usrSafes` and `usrSafesPerCollat` could be changed during the migration which could lead to unexpected results.
