### ISSUE TITLE
Fix ExitCollateral

### ISSUE THREAD

**Issue by daopunk** [open-dollar/od-contracts#425]
Audit issue 267 from Code4rena audit may have been a false positive, and the proposed fix has broken some functionality. Relevant changes to the protocol have been noted below.

Objectives:
- Determine if original audit issue was a false positive
- Determine if changes made to fix issue should be reverted or kept
- Determine if new changes should be made
- Explain how collateral exit should occur

Please do write-up, before making code changes.

**Original audit issue:**
https://github.com/open-dollar/od-contracts/issues/215

**PR Fix for Audit:**
https://github.com/open-dollar/od-contracts/pull/226/files

**Other Relevant Changes:**

- order of operations changed here:
https://github.com/open-dollar/od-contracts/pull/298/files

- handler exists check added:
https://github.com/open-dollar/od-contracts/commit/547c840df2b1cfa7ec39f34b4d0ab67c473b84ae

**Comment by MrDeadCe11** [comment]
The problem with the implemented fix [here](https://github.com/open-dollar/od-contracts/blob/c7371d525422c18b0ce96d4778fc2aa5c9fc9feb/src/contracts/proxies/ODSafeManager.sol#L210)  is that it's checking to make sure that the funds are being transfered to the [safeHandler contract](https://github.com/open-dollar/od-contracts/blob/c7371d525422c18b0ce96d4778fc2aa5c9fc9feb/src/contracts/proxies/SAFEHandler.sol#L16) that is created when a safe is opened.

Funds sent to a safeHandler would be lost as there is no way to transfer erc20 tokens back out of the contract once received.  Additionally there is no fallback to receive native tokens.  

The initial issue [#215](https://github.com/open-dollar/od-contracts/issues/215) is a non-issue, because so long as the ODProxy is calling the function.  The proxy should be able to send the funds wherever it likes.  If they want to withdraw to the same wallet that deposited the funds or to a different wallet shouldn't matter, so long as the authorized owner is making the call and this is already checked in the [safeAllowed](https://github.com/open-dollar/od-contracts/blob/c7371d525422c18b0ce96d4778fc2aa5c9fc9feb/src/contracts/proxies/ODSafeManager.sol#L208) in the [safeAllowed](https://github.com/open-dollar/od-contracts/blob/c7371d525422c18b0ce96d4778fc2aa5c9fc9feb/src/contracts/proxies/ODSafeManager.sol#L56-L61) modifier.

We have two options
1.  Remove the safeHandler check.
or
2. change it to check that the destination is the ODProxy or the owner of the ODProxy if we want to limit where collateral can be transferred to.

**Comment by pi0neerpat** [comment]
Let's proceed with option 1
