### ISSUE TITLE
Proxy Repay Debt without Withdrawing

### ISSUE THREAD

**Issue by daopunk** [open-dollar/od-contracts#481]
Repay debt is prevented without withdrawing some amount of collateral

**Comment by pi0neerpat** [comment]
Related to #443

**Comment by MrDeadCe11** [comment]
> Related to #443

Thanks, I'm working on it right now.

**Comment by MrDeadCe11** [comment]
The deployed basic actions contract had not implemented taxSingle() in the repay debt function.  I added it and deployed a new basic actions contract and it fixed the underflow.  However a new issue arrises in the CommonActionsContract where when approval is being granted for the ERC20 transfer it reverts because of a SafeERC20 check when approving the coinJoin contract to take the COIN amount.
 
`revert: SafeERC20: approve from non-zero to non-zero allowance`

the solution to this would be to check it the CoinJoin contract already had approval and then use SafeERC20.safeIncreaseAllowance() rather than approve.

this requires modifying the Common actions Contract and re-deploying it.

**Comment by pi0neerpat** [comment]
Excellent writeup. I really enjoy reading your updates on these. Very clear and concise.
