### ISSUE TITLE
OD-11 CollateralJoin UX

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#538]
Audit

**Comment by MrDeadCe11** [comment]
collateral enter flow:

collateral is entered into the system by calling lockCollateralAndGenerateDebt on BasicActions.sol.  This will transfer from the user account to the user proxy and then to the collateralJoinChild of that collateral type.  then an internal representation of the collateral is modified in the safeEngine to represent the safeHandler address owning that collateral.

collateralJoinChild.join(safeHandlerAddress, amout);

Exit flow:
transferCollateral is called on the ODSafeManager.  this transfers collateral from the safe handler to the dst address (this is an internal representation of ownership of the collateral and does not transfer any erc20).

the eoa that has received the transfer of internal collateral calls exit() on the collateral join child.  This destroys the internal representation of the collateral and then sends the ERC20 from the child to the address specified in the exit call.

actual erc20 Collateral is always held by the collateralJoinChild and not by the safe handler address.

Internal representations of the Collateral are modified by the safe engine with “modifyCollateralBalance” in order for the collateral to be tracked and “owned” by individual safes.

ModifyCollateralBalance does not check the existence of a safe in order to modify the balance.  However an underflow with happen if collateral that doesn’t exist is transferred.

If a collateralJoinChild is disabled and replaced with another child for the same collateral type the protocol will have to exit all collateral from the disabled contract in order to move it into the new child.  

Ddebt and collateral tracked by the safe engine doesn’t change according to the collateralChild being used but by the collateral type and the safeHandler address.  So collateral being exited from the system should exit out of the disabled collateralChild first, until that contract has been emptied before being exited out of the new collateralChild.

Reccomendations:

if a collateralChild is disabled all exiting collateral should be exited out of that contract untill the balance is 0.

coinJoin.join could check if the safeHandler address being passed in is a valid safe.

**Comment by pi0neerpat** [comment]
Paul to create an issue to enforce `safeHandler` during `coinjoin.join()`

**Comment by pi0neerpat** [comment]
Comple
