### ISSUE TITLE
Actions: Research

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#712]
- [x] Get a hands-on feel for existing user-experiences for leverage
- [x] Look for existing libraries/code we can use directly or use as reference

Places to start:
- Research Maker CDP leverage
- Instadapp
- Zapper

**Comment by daopunk** [comment]
General observations:
- CEXs offer much higher leverage than DEXs (e.g. 2000X vs. 50X upper limits)
- platforms that provide leverage often provide the choice to short or long a position
- based on current design, OpenDollar will only allow leveraging for long positions, but not shorting(?)
- gas fees are a notable factor for the profitability of leveraging on Mainnet (pushes out small users)

Hands-on testing:
- Aave UI testnet on Sepolia: https://staging.aave.com/
	- has many test ERC20s that can be easily minted
	- supplying and borrowing actions allowed
- Camelot, Uniswap, Sushiswap do not provide UIs for their testnets
	- after borrowing against collateral on Aave, there is nowhere to leverage the debt

MakerDAI
- website has outdated links
- some developer resources are no longer maintained
- community forum has splintered into many various projects
- nothing found in regards to tools for leveraging

Instadapp
- provides leveraging tools (can leverage DAI from Instadapp dashboard)
- provides a number of useful tools integrated into various DeFi protocols

Zapper
- seems less useful than Instadapp, but similarly provides dashboard

Libraries
- no specific usable "leverage" library found
- found several DeFi tooling libraries in Python
- browsed Githubs of Instadapp, Zapper, and MakerDAI, but more time would be needed to throughly assess applicability of code to our project

Termilogy:
- nX (e.g. 10X, 20X) where "n" refers to the number of loops of leverage, not the multiple of the original collateral

Risks:
- non-leveraged positions are at risk of liquidation, but liquidated safe owner retains their minted debt (not a total loss)
- leveraged positions risk losing both collateral and debt, since the debt is leveraged for more collateral

**Comment by daopunk** [comment]
leverage of defisaver
https://dashboard.tenderly.co/public/defisaver-v2/prod-simulations/fork-simulation/1019a92f-c5bf-4010-a44e-f1f50ccc0379


supply ETH on instadapp
https://dashboard.tenderly.co/public/InstaDApp/dsa-simulations/fork-simulation/89508016-4233-4739-9e78-4fbec38d6024?hideSidebar=true


DefiSaver provides 100 Eth in simulation mode
InstaDapp relies on real balance for simulation mode

**Comment by daopunk** [comment]
slideshow w/ screenshots, notes

https://docs.google.com/presentation/d/1vrGU8XxfX420pxjeoIe09huWaNGm9uC5i8493y5dEog/edit?usp=sharing

**Comment by pi0neerpat** [comment]
Done
