### ISSUE TITLE
Renzo

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#723]
Research Renzo

**Comment by pi0neerpat** [comment]
Done. using chainlink

**Comment by MrDeadCe11** [comment]
## Renzo Finance

[Renzo](https://docs.renzoprotocol.com/docs) finance is a restaking manager for users who want to gain exposure eigenLayer and Symbiotic.  Users stake ETH with Renzo and receive ezETH in return.  EZETH is a yield bearing asset representing eth that has been restaked on eigenLayer and is accruing rewards.

Renzo has a [chainlink feed](https://arbiscan.io/address/0x11E1836bFF2ce9d6A5bec9cA79dc998210f3886d) for $ezEth but none for their other token offerings.  

#### Other token offerings:
 - $pzETH [(symbiotic restaking token)](https://docs.renzoprotocol.com/docs/renzo/usdpzeth), 
 - $REZ [(Renzo Protocol Token)](https://docs.renzoprotocol.com/docs/renzo/usdrez-staking/usdrez-staking-faqs), and 
 - $EIGEN [(eigenlayer rewards token)](https://docs.renzoprotocol.com/docs/renzo/usdeigen-staking)

None of these tokens are as popular as ezEth and seem to be less viable as a collateral type due to their lack of easily accessible price feeds.
